"""Update only title/OG/Twitter metadata, with auditable visible-copy evidence.

Dry run: python -X utf8 tools/personalize_title_suffixes.py
Apply:   python -X utf8 tools/personalize_title_suffixes.py --write
Verify:  python -X utf8 tools/personalize_title_suffixes.py --check
Run after any page generator; no manuscript is regenerated by this tool.
"""
from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from concurrent.futures import ThreadPoolExecutor
import hashlib
import html
import json
import math
from pathlib import Path
import re
from urllib.parse import unquote, urlparse, urljoin

from html.parser import HTMLParser
from title_suffix_rules import RULES, HUB_SUFFIXES, REDUNDANT, INTENTS

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / 'tools/reports/title-suffix-audit.json'
TITLE_RE = re.compile(r'(<title\b[^>]*>)(.*?)(</title>)', re.I | re.S)
META_RE = re.compile(r'<meta\b[^>]*>', re.I | re.S)
ATTR_RE = re.compile(r'''([:\w-]+)\s*=\s*(["'])(.*?)\2''', re.S)
SECTION_RE = re.compile(r'<section\b([^>]*)>(.*?)</section>', re.I | re.S)
BLOCK_RE = re.compile(r'<(h2|h3|p)\b[^>]*>(.*?)</\1>', re.I | re.S)
COMPILED = [(label, subject, re.compile(pattern), specificity) for label, subject, pattern, specificity in RULES]
BASELINE_COMMIT = '4914e1e366928ccb9ab93e50493270bf14232be8'
DOMAIN = 'https://xn--sp5b72l1taf0p.com'
COURSES = {'초등영어학원','초등수학학원','중등영어학원','중등수학학원','고등영어학원','고등수학학원'}


def clean(value):
    return ' '.join(html.unescape(re.sub(r'<[^>]+>', ' ', value)).split())


def attrs(tag):
    return {key.lower(): html.unescape(value) for key, _, value in ATTR_RE.findall(tag)}


def title_of(source):
    match = TITLE_RE.search(source)
    if not match:
        raise ValueError('missing title')
    return html.unescape(match[2]).strip()


def replace_titles(source, title):
    escaped = html.escape(title, quote=True)
    source, count = TITLE_RE.subn(lambda m: m[1] + escaped + m[3], source)
    if count != 1:
        raise ValueError(f'title count {count}')

    def meta(match):
        tag = match[0]
        data = attrs(tag)
        if data.get('property') != 'og:title' and data.get('name') != 'twitter:title':
            return tag
        tag, n = re.subn(r'''(\bcontent\s*=\s*)(["'])(.*?)\2''',
                        lambda m: m[1] + m[2] + escaped + m[2], tag, flags=re.S)
        if n != 1:
            raise ValueError('title meta content is missing')
        return tag

    return META_RE.sub(meta, source)


def masked(source):
    """Byte-level guard: ALL content except the three allowed values is fixed."""
    return replace_titles(source, '__TITLE_ONLY__')


def sha(value):
    return hashlib.sha256(value.encode('utf-8')).hexdigest()


class CopyParser(HTMLParser):
    """Extract text blocks with their real ancestor context, including nested sections."""
    VOID = {'area','base','br','col','embed','hr','img','input','link','meta','param','source','track','wbr'}
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.stack=[]; self.captures=[]; self.blocks=[]
    def handle_starttag(self,tag,attributes):
        if tag in self.VOID:return
        node=(tag,dict(attributes)); self.stack.append(node)
        if tag in ('p','h2','h3','h4','li'):
            self.captures.append(dict(node=node,context=list(self.stack),text=[]))
    def handle_startendtag(self,tag,attributes):
        pass
    def handle_data(self,data):
        for item in self.captures:item['text'].append(data)
    def handle_endtag(self,tag):
        index=next((i for i in range(len(self.stack)-1,-1,-1) if self.stack[i][0]==tag),None)
        if index is None:return
        removed=self.stack[index:]; self.stack=self.stack[:index]
        for item in self.captures[:]:
            if any(item['node'] is node for node in removed):
                text=' '.join(''.join(item['text']).split())
                if text:self.blocks.append((item['node'][0],text,item['context']))
                self.captures.remove(item)


def learning_blocks(main,kind):
    parser=CopyParser();parser.feed(main)
    result=[];seen=set(); plan_paragraph=0
    for tag,value,context in parser.blocks:
        if len(value)<12:continue
        attributes=' '.join(d.get('class','')+' '+d.get('id','') for _,d in context)
        tokens=set(attributes.split())
        if any(t in ('nav','script','style','aside','footer') for t,_ in context):continue
        if any('hidden' in d or re.search(r'display\s*:\s*none',d.get('style','')) for _,d in context):continue
        if any(word in attributes for word in ('verified-center','verified-note','faq-section','review-card','internal-links','hero-center-fact','hero-mini-panel','category-region','hub-district','subject-media')):
            continue
        # Center registration, school lists and availability are not learning evidence.
        if re.match(r'제공된 참고 학교|센터 자료의 가능 학년|자료 기준:|실제 방문 주소|학교 정보가 확인|확인된 학교 정보에는',value):
            if not ('subject-article' in tokens and len(value)>230):continue
        weight=0
        if kind=='subject':
            if 'subject-article' in tokens:
                weight=4.0
                if 'subject-prose-section' not in tokens:weight=5.5
                if tag=='h2':weight+=1
                if '학교' in value and tag=='h2' and ('주소' in value or '정보' in value):weight=0
            elif 'subject-answer-card' in tokens:weight=2.5
            elif 'local-hero' in tokens and tag=='p':weight=2
        else:
            if 'learning-plan' in tokens:
                if tag=='p':
                    weight=5 if plan_paragraph==0 else 1.5
                    plan_paragraph+=1
                elif tag=='li':weight=2.7
                else:weight=2
            elif 'local-hero' in tokens and tag=='p':
                weight=4
                # The same paragraph may append address/availability sentences;
                # prioritize its actual learning answer and student situation.
                value=' '.join(re.split(r'(?<=[.!?])\s+',value)[:2])
            elif 'geo-answer-card' in tokens:weight=3.3
            elif 'geo-check-card' in tokens:weight=1.2
        if weight and value not in seen:
            result.append((value,weight));seen.add(value)
    return result


def read_page(path):
    source=path.read_bytes().decode('utf-8')
    title=title_of(source);base=re.split(r'[|｜]',title,maxsplit=1)[0].strip()
    rel=path.relative_to(ROOT).as_posix();parts=rel.split('/')[:-1]
    match=re.search(r'<main\b[^>]*>(.*?)</main>',source,re.I|re.S)
    if not match:raise ValueError(f'missing main: {rel}')
    main=match[1]
    canonical=re.search(r'<link\b(?=[^>]*rel=["\']canonical["\'])[^>]*href=["\']([^"\']+)',source,re.I)
    if not canonical:raise ValueError(f'missing canonical: {rel}')
    url=html.unescape(canonical[1])
    if not url.startswith(DOMAIN+'/'):raise ValueError(f'wrong site canonical: {url}')
    if parts[0]=='전국센터':
        if len(parts)==3:
            kind='national-course';category=parts[-1]
        elif (path.parent/'고등수학학원/index.html').exists():
            kind='locality';category=''
        elif parts[1] in COURSES:
            kind='category';category=parts[1]
        else:
            kind='region';category=''
        group='전국센터/'+(category or kind)
    else:
        kind='category' if len(parts)==2 else 'subject'
        category=parts[1];group='과목별학원/'+category
    subject='math' if '수학' in category and '영수' not in category else 'english' if '영어' in category else ''
    younger=any(x in category for x in ('초등','중등','중학생'))
    visible=clean(re.sub(r'<(script|style)\b[^>]*>.*?</\1>','',main,flags=re.I|re.S))
    return dict(path=path,source=source,title=title,base=base,rel=rel,parts=parts,
                kind=kind,group=group,category=category,subject=subject,younger=younger,
                main=main,visible=visible,blocks=learning_blocks(main,kind),
                canonical=url)


def content_candidates(page):
    found=[]
    for label,subject,pattern,specificity in COMPILED:
        if page['subject'] and subject and page['subject']!=subject:continue
        if page['subject'] and label=='영어·수학 개별 진단':continue
        if page['younger'] and any(x in label for x in ('수능','모의고사')):continue
        if '초등' in page['category'] and any(x in label for x in ('내신','수행평가','시험 시간')):continue
        evidence=[];score=0
        intent_pattern=re.compile(INTENTS[label]) if label in INTENTS else None
        for block,weight in page['blocks']:
            match=pattern.search(block)
            intent=intent_pattern.search(block) if intent_pattern and weight>=4 else None
            if match or intent:
                effective=weight+3 if intent else weight
                evidence.append((block,(intent or match)[0],effective));score+=weight
        if evidence:
            best=max(evidence,key=lambda x:x[2])
            position=best[0].index(best[1])
            excerpt=best[0][max(0,position-90):position+len(best[1])+180]
            found.append(dict(label=label,subject=subject,
                              score=(best[2]*4+min(score,14))*specificity,
                              excerpt=excerpt,match=best[1]))
    return found


def directory_suffix(page):
    key='/'.join(page['parts'])
    if key in HUB_SUFFIXES:
        label,terms=HUB_SUFFIXES[key]
        # Restrict evidence to the introduction before directory links.
        intro=page['visible'].split('LOCAL DIRECTORY')[0].split('LOCAL SEARCH')[0]
        for term in terms:
            if term not in intro:raise ValueError(f'{key}: missing introductory evidence {term}')
        return label,[dict(label=label,match=' / '.join(terms),excerpt=intro[:1000],terms=terms)]
    if page['kind']=='region':
        visible=page['visible']
        districts=re.search(r'(\d+)개 시·군·구',visible)
        localities=re.search(r'(\d+)개 동네',visible)
        if not districts or not localities:raise ValueError(f'{key}: directory counts missing')
        urls={unquote(urlparse(urljoin(page['canonical'],html.unescape(x))).path).strip('/')
              for x in re.findall(r'<a\b[^>]*href=["\']([^"\']+)',page['main'])}
        children=[x for x in urls if len(x.split('/'))==2 and x.startswith('전국센터/')
                  and (ROOT/x/'고등수학학원/index.html').exists()]
        if len(children)!=int(localities[1]):raise ValueError(f'{key}: directory link count mismatch')
        label=f'{districts[1]}개 시군구·{localities[1]}개 동네 안내'
        return label,[dict(label=label,match=districts[0]+' / '+localities[0],
                           excerpt=visible[:700],terms=[districts[0],localities[0]])]
    raise ValueError(f'unhandled directory {key}')


def plan(pages):
    grouped=defaultdict(list)
    for page in pages:
        if page['kind'] in ('subject','locality','national-course'):
            page['candidates']=content_candidates(page)
            if len(page['candidates'])<2:
                raise ValueError(f'{page["rel"]}: fewer than two supported learning topics')
            grouped[page['group']].append(page)
        else:
            page['suffix'],page['evidence']=directory_suffix(page)

    for group, members in grouped.items():
        frequencies=Counter(c['label'] for p in members for c in p['candidates'])
        used=Counter()
        for page in members:
            candidates=page['candidates']
            for c in candidates:
                subject_boost=1.12 if (page['subject'] and c['subject']) else 1
                c['rank']=c['score']*subject_boost*(1 + .15*math.log((len(members)+1)/(frequencies[c['label']]+1)))
            candidates.sort(key=lambda c:(-c['rank'],c['label']))
            if page['subject']:
                specific=[c for c in candidates if c['subject']==page['subject']]
                if not specific:
                    raise ValueError(f'{page["rel"]}: no subject-specific evidence')
            else:
                specific=candidates
            # Alternatives are limited to evidence close to the strongest topic.
            firsts=[c for c in specific[:8] if c['rank']>=specific[0]['rank']*.90]
            pairs=[]
            for first in firsts:
                for second in candidates[:16]:
                    if first is second or first['label'] in second['label'] or second['label'] in first['label']:
                        continue
                    redundant_groups=REDUNDANT
                    if any({first['label'],second['label']}<=family for family in redundant_groups):
                        continue
                    if len(set(first['label'].split()) & set(second['label'].split()))>1:
                        continue
                    suffix=first['label']+'·'+second['label']
                    if len(suffix)>34 or len(page['base']+' | '+suffix)>75:
                        continue
                    pair_key=tuple(sorted((first['label'],second['label'])))
                    score=first['rank']+second['rank']*.66 - min(used[pair_key],6)*.8
                    pairs.append((score,suffix,first,second))
            if not pairs:
                raise ValueError(f'{page["rel"]}: no concise supported pair')
            _,suffix,first,second=max(pairs,key=lambda x:(x[0],x[1]))
            page['suffix']=suffix
            page['evidence']=[{k:c[k] for k in ('label','match','excerpt')} for c in (first,second)]
            used[tuple(sorted((first['label'],second['label'])))]+=1

    for p in pages:
        p['new_title']=p['base']+' | '+p['suffix']
        p['updated']=replace_titles(p['source'],p['new_title'])
        if masked(p['source'])!=masked(p['updated']):
            raise ValueError(f'{p["rel"]}: non-title content changed')
        if len(p['suffix'])>40 or len(p['new_title'])>85:
            raise ValueError(f'{p["rel"]}: overly long title')
        if p['new_title'].count('|')!=1:
            raise ValueError(f'{p["rel"]}: separator count')
        for meta in [attrs(m[0]) for m in META_RE.finditer(p['updated'])]:
            if meta.get('property')=='og:title' or meta.get('name')=='twitter:title':
                if meta.get('content')!=p['new_title']:
                    raise ValueError(f'{p["rel"]}: social title mismatch')
    if len({p['new_title'] for p in pages})!=len(pages):
        raise ValueError('duplicate complete titles')


def rss_update(pages):
    path=ROOT/'rss.xml'
    source=path.read_bytes().decode('utf-8')
    by_url={unquote(p['canonical']):p for p in pages}
    count=0
    def item(m):
        nonlocal count
        block=m[0]
        link=re.search(r'<link>(.*?)</link>',block,re.S)
        if not link:return block
        page=by_url.get(unquote(html.unescape(link[1])))
        if not page:return block
        new=re.sub(r'(<title>).*?(</title>)',lambda x:x[1]+html.escape(page['new_title'])+x[2],block,count=1,flags=re.S)
        count+=new!=block
        return new
    updated=re.sub(r'<item>.*?</item>',item,source,flags=re.S)
    return source,updated,count


def run():
    parser=argparse.ArgumentParser()
    mode=parser.add_mutually_exclusive_group()
    mode.add_argument('--write',action='store_true')
    mode.add_argument('--check',action='store_true')
    args=parser.parse_args()
    paths=sorted(p for top in ('전국센터','과목별학원') for p in (ROOT/top).rglob('index.html') if p.parent!=ROOT/top)
    if len(paths)!=5220:
        raise ValueError(f'expected 5220 descendants, found {len(paths)}')
    with ThreadPoolExecutor(max_workers=8) as pool:
        pages=list(pool.map(read_page,paths))
    plan(pages)
    rss_old,rss_new,rss_changes=rss_update(pages)
    stats={}
    for group in sorted({p['group'] for p in pages}):
        members=[p for p in pages if p['group']==group]
        counts=Counter(p['suffix'] for p in members)
        stats[group]=dict(pages=len(members),uniqueSuffixes=len(counts),mostRepeated=counts.most_common(4))
    changed=[p for p in pages if p['source']!=p['updated']]
    old_entries={}
    if REPORT.exists():
        old_entries={row['path']:row for row in json.loads(REPORT.read_text(encoding='utf-8'))['entries']}
    def before_title(p):
        old=old_entries.get(p['rel'])
        if old and old['unchangedContentSha256']==sha(masked(p['source'])):
            return old['before']
        return p['title']
    report=dict(site=DOMAIN,baselineCommit=BASELINE_COMMIT,pages=len(pages),changedThisRun=len(changed),
                changedFromOriginal=sum(before_title(p)!=p['new_title'] for p in pages),rssTitlesChanged=rss_changes,
                uniqueTitles=len({p['new_title'] for p in pages}),
                uniqueSuffixes=len({p['suffix'] for p in pages}),
                titleLength=dict(min=min(len(p['new_title']) for p in pages),max=max(len(p['new_title']) for p in pages)),
                nonTitleChanges=0,sitemapSha256=hashlib.sha256((ROOT/'sitemap.xml').read_bytes()).hexdigest(),groups=stats,entries=[dict(path=p['rel'],url=p['canonical'],kind=p['kind'],group=p['group'],
                  before=before_title(p),after=p['new_title'],suffix=p['suffix'],
                  unchangedContentSha256=sha(masked(p['source'])),
                  unchangedNormalizedContentSha256=sha(masked(p['source']).replace('\r\n','\n')),
                  evidence=p['evidence']) for p in pages])
    if args.write:
        REPORT.parent.mkdir(parents=True,exist_ok=True)
        for p in changed:
            p['path'].write_bytes(p['updated'].encode('utf-8'))
        if rss_old!=rss_new:
            (ROOT/'rss.xml').write_bytes(rss_new.encode('utf-8'))
        REPORT.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
    elif not args.check:
        REPORT.parent.mkdir(parents=True,exist_ok=True)
        REPORT.with_name('title-suffix-plan.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
    print(json.dumps({k:v for k,v in report.items() if k!='entries'},ensure_ascii=False,indent=2))
    for p in [p for p in pages if '명일' in p['rel']][:14]:
        print(p['new_title'])
    if args.check and (changed or rss_changes):
        raise SystemExit('FAIL: generated titles are not up to date')
    print('TITLE_SUFFIX_'+('CHECK' if args.check else 'WRITE' if args.write else 'PLAN')+'_PASS')


if __name__=='__main__':
    run()
